### ISSUE TITLE
Month range parsing issue

### ISSUE THREAD

**Issue by RCMainak** [JoshOY/quartz-cron-parser#5]
Hello @JoshOY, hope you're doing well.

I found an edge case where the parser is failing to parse the quartz expression. Kindly check the below testcase for reference,
```
[
    '4,0,1,2 0 12 ? JAN-JUN *',
    {
      error: null,
      result: [
        { field: 'seconds', mode: 'specific', value: [4, 0, 1, 2] },
        { field: 'minutes', mode: 'specific', value: 0 },
        { field: 'hours', mode: 'specific', value: 12 },
        { field: 'dayOfMonth', mode: 'noSpecific', value: '?' },
        { field: 'month', mode: 'range', value: [1,6] },
        { field: 'dayOfWeek', mode: 'every', value: '*' },
      ],
    },
  ],
```

In the above testcase the parser is failing with error,
```
Error: Syntax error at line 1 col 19:
    
    1 4,0,1,2 0 12 ? JAN-JUN *
                        ^
    
    Unexpected "-". Instead, I was expecting to see one of the following:
    
    A "," based on:
        specificMonths → specificMonthString ● "," specificMonths
        _month →  ● specificMonths
        month →  ● _month
        quartzCronExprFields → seconds  minutes  hours  dayOfMonth  ● month _ dayOfWeek
        quartzCronExpr →  ● quartzCronExprFields
    A character matching /[ ]/ based on:
        _$ebnf$1 →  ● /[ ]/
         →  ● $ebnf$1
        quartzCronExprFields → seconds  minutes  hours  dayOfMonth  month ●  dayOfWeek  years
        quartzCronExpr →  ● quartzCronExprFields
```

I've checked with other parsers the above expression is a valid expression and I've added the expected output in the testcase for your reference. Thank you.

**Comment by JoshOY** [comment]
Hi @RCMainak , thank you for reporting this bug. I've just tried to fix it in [this commit](https://github.com/JoshOY/quartz-cron-parser/commit/295bbde90403f3a108c2838393dbb08f7556ebc4).
Please try bump `@joshoy/quartz-cron-parser` to version 0.1.6 and check it ;-)

**Comment by RCMainak** [comment]
Thanks @JoshOY it works as expected. I've found another bug. I'll create an new issue & try to fix it myself 🤞
